# Generated by Django 3.2 on 2021-07-15 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20210713_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=3000)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 846504, tzinfo=utc))),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.CharField(default=None, max_length=400, null=True)),
                ('deleted_by', models.CharField(default=None, max_length=400, null=True)),
                ('updated_by', models.CharField(default=None, max_length=400, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='bousermodel',
            name='is_encrypt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantmodel',
            name='is_charge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantmodel',
            name='is_encrypt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 815246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 846504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 846504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 815246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 815246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 830873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 815246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledgermodel',
            name='trans_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 815246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 830873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 815246, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 830873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 830873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 830873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 830873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 9, 45, 35, 846504, tzinfo=utc)),
        ),
    ]
