# Generated by Django 3.2.4 on 2021-07-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_auto_20210726_1546'),
        ('apis', '0027_auto_20210726_2204'),
    ]

    operations = [
    ]
