# Generated by Django 3.2 on 2021-08-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0045_auto_20210802_1025'),
        ('apis', '0051_auto_20210802_1905'),
    ]

    operations = [
    ]
