# Generated by Django 3.2 on 2021-08-05 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0054_auto_20210805_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 251765)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 267769)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 267769)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 255765)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 255765)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 259766)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 263767)),
        ),
        migrations.AlterField(
            model_name='mercahantmodemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 271769)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 247761)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 259766)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 263767)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 259766)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 259766)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 267769)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='bene_account_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='bene_account_number',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='bene_ifsc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 251765)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='credit_transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 251765), null=True),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 263767)),
        ),
        migrations.AlterField(
            model_name='webhookmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 8, 1, 4, 271769)),
        ),
    ]
