
# Generated by Django 3.2.4 on 2021-08-05 15:47


# Generated by Django 3.2 on 2021-08-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0056_auto_20210805_1548'),
        ('apis', '0057_auto_20210805_1229'),
    ]

    operations = [
    ]
