# Generated by Django 3.2 on 2021-08-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0074_auto_20210823_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyledgermodel',
            name='closing_credit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyledgermodel',
            name='closing_debit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyledgermodel',
            name='opening_credit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyledgermodel',
            name='opening_debit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 530363)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 640759)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 636079)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 561259)),
        ),
        migrations.AlterField(
            model_name='dailyledgermodel',
            name='closing_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyledgermodel',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 545828)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 568595)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 599594)),
        ),
        migrations.AlterField(
            model_name='mercahantmodemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 706584)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 522362)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 594177)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 610776)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 581833)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 570750)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 644528)),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 790182)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 536165)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 627358)),
        ),
        migrations.AlterField(
            model_name='webhookmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 43, 40, 696093)),
        ),
    ]
