# Generated by Django 4.0.1 on 2022-01-17 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0082_auto_20211101_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 280519)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 298522)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 296535)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 284520)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 283519)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 287519)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 292521)),
        ),
        migrations.AlterField(
            model_name='mercahantmodemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 302521)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 278519)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 291521)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 294521)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 289522)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 288519)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 299522)),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 308521)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 281525)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 295522)),
        ),
        migrations.AlterField(
            model_name='webhookmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 12, 48, 41, 301521)),
        ),
        migrations.CreateModel(
            name='CIBRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aggrName', models.CharField(blank=True, max_length=100, null=True)),
                ('aggrId', models.CharField(blank=True, max_length=100, null=True)),
                ('corpId', models.CharField(blank=True, max_length=100, null=True)),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('aliasId', models.CharField(blank=True, max_length=100, null=True)),
                ('urn', models.CharField(default=uuid.uuid4, max_length=50)),
                ('errorMessage', models.CharField(blank=True, max_length=100, null=True)),
                ('response', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('errorCode', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.bankpartnermodel')),
            ],
        ),
    ]
