# Generated by Django 4.0.1 on 2022-01-17 15:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0084_cibregistration_merchantid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICICI_Beneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchantId', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_beneficiary_id', models.CharField(blank=True, max_length=10, null=True)),
                ('aggrName', models.CharField(blank=True, max_length=100, null=True)),
                ('aggrId', models.CharField(blank=True, max_length=100, null=True)),
                ('corpId', models.CharField(blank=True, max_length=100, null=True)),
                ('corpUsr', models.CharField(blank=True, max_length=100, null=True)),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('payeeType', models.CharField(default='W', max_length=2)),
                ('urn', models.CharField(default=uuid.uuid4, max_length=50)),
                ('errorMessage', models.CharField(blank=True, max_length=100, null=True)),
                ('response', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('errorCode', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 822918)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 850919)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 847920)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 829919)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 827917)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 833917)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 841919)),
        ),
        migrations.AlterField(
            model_name='mercahantmodemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 856920)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 820919)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 839918)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 843918)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 837921)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 835920)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 852924)),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 864920)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 824918)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 845919)),
        ),
        migrations.AlterField(
            model_name='webhookmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 20, 41, 30, 854920)),
        ),
    ]
