# Generated by Django 4.0.1 on 2022-01-23 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0092_cibregistration_merchantaccountnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccountDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.IntegerField(default=0)),
                ('merchantId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(max_length=12)),
                ('merchantAccountNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('ifscCode', models.CharField(max_length=20)),
                ('upiId', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('deletedAt', models.DateTimeField(default=None, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 898171)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 918171)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 917171)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 903167)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='max_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='min_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 902167)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 906168)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 911168)),
        ),
        migrations.AlterField(
            model_name='mercahantmodemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 923167)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 896167)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 910168)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 913167)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 909167)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 907169)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 920166)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='max_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='min_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 930167)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 900167)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 915170)),
        ),
        migrations.AlterField(
            model_name='webhookmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 14, 9, 33, 921168)),
        ),
    ]
