# Generated by Django 4.0.1 on 2022-02-02 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0099_remove_icici_beneficiary_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='remitter_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='retailer_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistorymodel',
            name='trans_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankpartnermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 936987)),
        ),
        migrations.AlterField(
            model_name='beneficiarymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 959020)),
        ),
        migrations.AlterField(
            model_name='bousermodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 958023)),
        ),
        migrations.AlterField(
            model_name='chargemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 945048)),
        ),
        migrations.AlterField(
            model_name='featuremodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 943998)),
        ),
        migrations.AlterField(
            model_name='ipwhitelistedmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 947987)),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 953024)),
        ),
        migrations.AlterField(
            model_name='mercahantmodemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 963023)),
        ),
        migrations.AlterField(
            model_name='merchantmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 934988)),
        ),
        migrations.AlterField(
            model_name='modemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 952023)),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 954987)),
        ),
        migrations.AlterField(
            model_name='rolefeaturemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 951022)),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 950040)),
        ),
        migrations.AlterField(
            model_name='slabmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 960022)),
        ),
        migrations.AlterField(
            model_name='taxmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 967024)),
        ),
        migrations.AlterField(
            model_name='transactionhistorymodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 941032)),
        ),
        migrations.AlterField(
            model_name='useractivemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 955989)),
        ),
        migrations.AlterField(
            model_name='webhookmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 45, 20, 962022)),
        ),
    ]
