# Generated by Django 3.2.9 on 2022-03-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0085_alter_bankpartnermodel_created_at_and_more'),
        ('apis', '0100_transactionhistorymodel_remitter_name_and_more'),
    ]

    operations = [
    ]
